### ISSUE TITLE
打开自动提交答案功能后无法跳转到下一个任务点

### ISSUE THREAD

**Issue by cape1999** [AntaresQAQ/chaoxing-autoflush-wanshiwu#1]

**Comment by AntaresQAQ** [comment]
目前我这里测试似乎在题目切换上面没有问题，不久前修复了一些小问题。

请重新安装脚本后确保`setting.work` 、 `setting.jump` 和 `setting.auto` 的值均为 `1`

十分感谢您帮助测试！

**Comment by AntaresQAQ** [comment]
fixed
